%Define model parameters:
%     a_T: T7-monomer production rate
%     a_C: CAT production rate
%     K_G: Km of T7-promoter gene expression's dependency on T7 dimers
%     hon_min: minimal dimerization rate
%     hon_max: maximal dimerization rate
%     hoff_min: minimal dimer dissociation rate
%     K_L_on: Km of dimerization reaction's dependency on light
%     n_L_on: Hill coefficient of dimerization reaction's dependency on light
%     n_G: Hill coefficient of T7-Promoter activation
%     h_C: hill-exponent of CAM degradation
%     mol2fluo: Conversion factor from molecules to flow cytometry arbitrary 
%     fluorescence units
%     N_p: p15A plasmid copy number (CAT gene)
%     K_D: Km of CAM-ribosome binding reaction
%     K_C: Km of CAM-degradation reaction by CAT divided by its k_cat
%     k: CAM diffusion rate
%     n_r: effective ribosomal protein length (aa)
%     n_T: length of T7-monomer (average between N- and C-term
%     n_C: length of CAT
%     g_0: Average translation rate per ribosome
%     phi_max: Maximal proteome fraction occupied by ribosomes
%     phi_0: Proteome fraction of inactive ribosomes
%     d_cell: Cell density (conversion factor to go from proteome fractions
%     to molecules per cell
%     nu: Nutrient capacity of medium (LB)
%     A_ext: External concentration of CAM

%Load previously optimized parameters values of the photophilic strain
opt_params = load('opt_params.mat');
    
%General Parameters:

p_var = [opt_params.x(1);...%.p_var_struct.a_T;...
         opt_params.x(2);...%.p_var_struct.a_C;...
         opt_params.x(3);...%.p_var_struct.K_G;...
         opt_params.x(4);...%.p_var_struct.hon_min;...
         opt_params.x(5);...%.p_var_struct.hon_max;...
         opt_params.x(6);...%.p_var_struct.K_L_on;...
         opt_params.x(7);...%.p_var_struct.n_L_on;...
         opt_params.x(8);...%.p_var_struct.n_G;...
         opt_params.x(9);...%.p_var_struct.h_C;...
         opt_params.x(10);...%.p_var_struct.mol2fluo;...
         opt_params.x(11)];%.p_var_struct.L_0];
     
p_fix = [opt_params.p_fix_struct.N_p;...
         opt_params.p_fix_struct.K_D;...
         opt_params.p_fix_struct.K_C;...
         opt_params.p_fix_struct.k;...
         opt_params.p_fix_struct.n_r;...
         opt_params.p_fix_struct.n_T;...
         opt_params.p_fix_struct.n_C;...
         opt_params.p_fix_struct.g_0;...
         opt_params.p_fix_struct.phi_max;...
         opt_params.p_fix_struct.phi_0;...
         opt_params.p_fix_struct.d_cell;...
         opt_params.p_fix_struct.nu;...
         opt_params.p_fix_struct.A_ext];